### PR TITLE
Fix several issues

### PR DESCRIPTION
**Pull request by vkhramtsov**
- [x] Remove obsolete use statements
- [x] Fix php docs
- [x] Remove array usage where we can use simple compare
- [x] Optimize some code
- [x] Remove methods with same body as in parent

### CODE REVIEW

**Comment by vkhramtsov** [comment]
Unfortunately I cannot fix time out, error 503 and expired certificate. As an option, I can restart this build later

**Comment by mpratt** [comment]
Hi @vkhramtsov !
Thanks for the PR, Ill be merging it later tonight. Dont worry about the failing tests I' ll take care of that, since your changes have nothing to do with them.

**Comment by vkhramtsov** [comment]
Hi. But I failed some tests with new code. Looks like everything is works as before now ;)

**Comment by mpratt** [comment]
Thanks for the PR, it has been merged. Tests are passing!
Changes are available on master now, I will be tagging another version as soon as I make more modifications to providers/endpoints or on bugfixes.

**Pull request merged**
